# -*- coding: utf-8 -*-
"""NLP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZInMekf2qi0RyOOE3ZeUNRIYKMd9G6Kf
"""

from __future__ import annotations

import html
import importlib.metadata
import importlib.util
import json
import math
import platform
import re
import shutil
import subprocess
import sys
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import numpy as np
import requests

# ==========================================
# 1. تنزيل المستودع والتحقق من البيئة البرمجية
# ==========================================

try:
    subprocess.run(
        ["git", "clone", "https://github.com/Manal-qaysi/Bayan_App_NLP3.git"],
        check=False
    )
except Exception as e:
    print("إشعار git clone:", e)

COURSE = "Bayan Applied NLP"
AUTHOR = "Manal Qaysi"


def package_version(name: str) -> str:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return "not-installed"


def gib(value: int) -> float:
    return round(value / (1024 ** 3), 2)


in_colab = importlib.util.find_spec("google.colab") is not None

torch_version = package_version("torch")
cuda_available = False
gpu_name = None

if torch_version != "not-installed":
    import torch

    cuda_available = bool(torch.cuda.is_available())

    if cuda_available:
        gpu_name = torch.cuda.get_device_name(0)

disk = shutil.disk_usage("/")

report = {
    "course": COURSE,
    "author": AUTHOR,
    "checked_at_utc": datetime.now(timezone.utc).isoformat(),
    "in_colab": in_colab,
    "python": platform.python_version(),
    "platform": platform.platform(),
    "device": "cuda" if cuda_available else "cpu",
    "gpu_name": gpu_name,
    "disk_free_gib": gib(disk.free),
    "packages": {
        "numpy": package_version("numpy"),
        "pandas": package_version("pandas"),
        "scikit-learn": package_version("scikit-learn"),
        "torch": torch_version,
    },
}

print(json.dumps(report, ensure_ascii=False, indent=2))

arabic_sample = "مرحبًا بكم في مشروع بيان"

core_checks_env = {
    "python_3_10_or_newer": sys.version_info >= (3, 10),
    "utf8_round_trip": (
        arabic_sample.encode("utf-8").decode("utf-8") == arabic_sample
    ),
    "numpy_available": report["packages"]["numpy"] != "not-installed",
    "pandas_available": report["packages"]["pandas"] != "not-installed",
    "sklearn_available": report["packages"]["scikit-learn"] != "not-installed",
    "torch_available": report["packages"]["torch"] != "not-installed",
    "disk_has_1_gib_free": report["disk_free_gib"] >= 1.0,
}

for name, passed in core_checks_env.items():
    print("✅" if passed else "❌", name)

BAYAN_ENV_READY = all(core_checks_env.values())

print("\nBAYAN_ENV_READY =", BAYAN_ENV_READY)

if not BAYAN_ENV_READY:
    raise RuntimeError("Environment check failed.")

sites = {
    "github_raw": "https://raw.githubusercontent.com/almiyead-rgb/bayan-applied-nlp-course/main/README.md",
    "pypi": "https://pypi.org/simple/",
    "huggingface_models": "https://huggingface.co/api/models/google-bert/bert-base-multilingual-cased",
}

connectivity = {}

for name, url in sites.items():
    try:
        response = requests.get(
            url,
            headers={"User-Agent": "Bayan-Course-Runtime-Doctor/1.1"},
            timeout=15,
            stream=True,
        )
        connectivity[name] = 200 <= response.status_code < 400
        response.close()
    except requests.RequestException:
        connectivity[name] = False

for name, passed in connectivity.items():
    print("✅" if passed else "⚠️", name)

report["connectivity"] = connectivity
report["core_checks"] = core_checks_env
report["bayan_env_ready"] = BAYAN_ENV_READY

report_path = Path("runtime_report.json")
report_path.write_text(
    json.dumps(report, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

print("Saved:", report_path)
print("Size:", report_path.stat().st_size, "bytes")

MOUNT_DRIVE = False

if MOUNT_DRIVE:
    if not in_colab:
        raise RuntimeError("Run this notebook in Google Colab.")

    from google.colab import drive

    drive.mount("/content/drive")
    recovery_dir = Path("/content/drive/MyDrive/bayan-nlp/recovery")
    recovery_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(report_path, recovery_dir / report_path.name)
    print("Copied report to:", recovery_dir)
else:
    print("Drive not mounted.")

print("\nBAYAN_ENV_READY =", BAYAN_ENV_READY)


# ==========================================
# 2. معالجة النصوص وتجزئتها (NLP & Tokenization)
# ==========================================

PINNED = {
    "transformers": "5.15.1",
    "tokenizers": "0.22.2",
    "spacy": "3.8.7",
}

missing = [name for name in PINNED if importlib.util.find_spec(name) is None]

if missing:
    packages = [f"{name}=={PINNED[name]}" for name in missing]
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])

import spacy
from tokenizers import Tokenizer
from tokenizers.models import WordPiece
from tokenizers.pre_tokenizers import BertPreTokenizer
from tokenizers.processors import TemplateProcessing

SEED = 42
rng = np.random.default_rng(SEED)

samples = [
    "أهلاً وسهلاً بكم في برنامج بيان!",
    "مرحبــاً\u00a0بكم",
    "Contact us at learner@example.org",
    "للتجربة فقط: 0551234567",
    "Natural language processing connects text and models.",
]

ARABIC_DIACRITICS = re.compile(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]")
TATWEEL = "\u0640"
WHITESPACE = re.compile(r"\s+")
HTML_TAG = re.compile(r"<[^>]+>")
EMAIL = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")
SAUDI_MOBILE = re.compile(r"(?<!\d)(?:\+?966|00966|0)?5\d{8}(?!\d)")


@dataclass(frozen=True)
class TextRecord:
    raw_text: str
    model_text: str


def inspect_unicode(text: str) -> list[dict[str, str]]:
    return [
        {
            "char": ch,
            "code_point": f"U+{ord(ch):04X}",
            "name": unicodedata.name(ch, "UNKNOWN"),
        }
        for ch in text
    ]


def mask_pii(text: str) -> str:
    text = EMAIL.sub("<EMAIL>", text)
    text = SAUDI_MOBILE.sub("<PHONE>", text)
    return text


def prepare_text(
    text: str,
    *,
    remove_diacritics: bool = False,
    normalize_alef: bool = False,
) -> TextRecord:
    if not isinstance(text, str):
        raise TypeError("text must be a string")

    raw = text
    model = unicodedata.normalize("NFC", html.unescape(text))
    model = HTML_TAG.sub(" ", model).replace(TATWEEL, "")

    if remove_diacritics:
        model = ARABIC_DIACRITICS.sub("", model)

    if normalize_alef:
        model = re.sub(r"[إأآٱ]", "ا", model)

    model = WHITESPACE.sub(" ", mask_pii(model)).strip()

    return TextRecord(raw_text=raw, model_text=model)


unicode_rows = inspect_unicode("أé")
assert unicode_rows[0]["code_point"] == "U+0623"

records = [prepare_text(text) for text in samples]

assert records[1].raw_text != records[1].model_text
assert "learner@example.org" not in records[2].model_text
assert "0551234567" not in records[3].model_text
assert records[2].raw_text == samples[2]

sentence_nlp = spacy.blank("xx")
sentence_nlp.add_pipe("sentencizer")


def split_model_sentences(text: str) -> list[str]:
    protected = prepare_text(text).model_text
    return [
        sentence.text.strip()
        for sentence in sentence_nlp(protected).sents
        if sentence.text.strip()
    ]


sentence_examples = {
    "ar": "الخدمة جيدة. لم يصل الرمز!",
    "en": "The portal stopped. Please retry.",
}

sentence_splits = {
    language: split_model_sentences(text)
    for language, text in sentence_examples.items()
}

assert sentence_splits["ar"] == ["الخدمة جيدة.", "لم يصل الرمز!"]
assert sentence_splits["en"] == ["The portal stopped.", "Please retry."]

special_tokens = ["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"]

known_tokens = [
    "أهلاً",
    "وسهلاً",
    "بكم",
    "في",
    "برنامج",
    "بيان",
    "!",
    "مرحبا",
    "Contact",
    "us",
    "at",
    "<",
    "EMAIL",
    ">",
    "Natural",
    "language",
    "processing",
    "connects",
    "text",
    "and",
    "models",
    ".",
]

vocab_tokens = special_tokens + known_tokens
vocab = {token: idx for idx, token in enumerate(vocab_tokens)}

local_tokenizer = Tokenizer(
    WordPiece(
        vocab=vocab,
        unk_token="[UNK]",
    )
)

local_tokenizer.pre_tokenizer = BertPreTokenizer()

local_tokenizer.post_processor = TemplateProcessing(
    single="[CLS] $A [SEP]",
    special_tokens=[
        ("[CLS]", vocab["[CLS]"]),
        ("[SEP]", vocab["[SEP]"]),
    ],
)

for record in records:
    encoded = local_tokenizer.encode(record.model_text)
    print(record.model_text)
    print("tokens:", encoded.tokens)
    print("ids:", encoded.ids)

assert local_tokenizer.encode("مرحبا بكم").tokens == [
    "[CLS]",
    "مرحبا",
    "بكم",
    "[SEP]",
]


def word_count(text: str) -> int:
    return max(1, len(text.split()))


def token_fertility(tokenizer: Tokenizer, text: str) -> float:
    tokens = tokenizer.encode(text).tokens
    content = [
        token for token in tokens if token not in {"[CLS]", "[SEP]", "[PAD]"}
    ]
    return len(content) / word_count(text)


def truncation_rate(
    tokenizer: Tokenizer,
    texts: Iterable[str],
    max_length: int,
) -> float:
    texts = list(texts)
    if not texts:
        raise ValueError("texts must not be empty")
    return sum(
        len(tokenizer.encode(text).ids) > max_length for text in texts
    ) / len(texts)


model_texts = [record.model_text for record in records]

fertilities = [
    token_fertility(local_tokenizer, text) for text in model_texts
]

rate_at_10 = truncation_rate(
    local_tokenizer,
    model_texts,
    max_length=10,
)

assert all(value > 0 for value in fertilities)
assert 0.0 <= rate_at_10 <= 1.0

MAX_LENGTH = 12

local_tokenizer.enable_truncation(max_length=MAX_LENGTH)
local_tokenizer.enable_padding(
    length=MAX_LENGTH,
    pad_id=vocab["[PAD]"],
    pad_token="[PAD]",
)

batch = [local_tokenizer.encode(text) for text in model_texts[:2]]

input_ids = np.array(
    [item.ids for item in batch],
    dtype=np.int64,
)

attention_mask = np.array(
    [item.attention_mask for item in batch],
    dtype=np.int64,
)

embedding_table = rng.normal(
    0.0,
    0.02,
    size=(len(vocab), 8),
)

embeddings = embedding_table[input_ids]

assert input_ids.shape == (2, MAX_LENGTH)
assert attention_mask.shape == input_ids.shape
assert embeddings.shape == (2, MAX_LENGTH, 8)

try:
    from transformers import AutoTokenizer

    hf_tokenizer = AutoTokenizer.from_pretrained(
        "google-bert/bert-base-multilingual-cased",
        use_fast=True,
    )

    comparison_text = (
        "معالجة اللغة الطبيعية مفيدة "
        "Natural language processing is useful"
    )

    hf_tokens = hf_tokenizer.tokenize(comparison_text)

    print("mBERT tokens:", hf_tokens)
    print("mBERT token count:", len(hf_tokens))
    print("Fast tokenizer:", hf_tokenizer.is_fast)

except Exception as exc:
    print("mBERT unavailable:", type(exc).__name__)

core_checks_nlp = {
    "unicode": unicode_rows[0]["code_point"] == "U+0623",
    "spacy_sentence_pipeline": all(
        len(value) == 2 for value in sentence_splits.values()
    ),
    "raw_copy_preserved": records[2].raw_text == samples[2],
    "pii_masked": (
        "<EMAIL>" in records[2].model_text and "<PHONE>" in records[3].model_text
    ),
    "token_metrics": (
        all(value > 0 for value in fertilities) and 0 <= rate_at_10 <= 1
    ),
    "embedding_shape": (embeddings.shape == (2, MAX_LENGTH, 8)),
}

for name, passed in core_checks_nlp.items():
    print(f"{name}: {'PASS' if passed else 'FAIL'}")

assert all(core_checks_nlp.values())


# ==========================================
# 3. آليات الانتباه ونماذج Transformer
# ==========================================

PINNED_TRANS = {
    "transformers": "5.15.1",
    "tokenizers": "0.22.2",
}

to_install = []
for distribution, expected in PINNED_TRANS.items():
    try:
        current = importlib.metadata.version(distribution)
    except importlib.metadata.PackageNotFoundError:
        current = None

    if current != expected:
        to_install.append(f"{distribution}=={expected}")

if to_install:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "--quiet", *to_install]
    )

print("NumPy:", np.__version__)
print(
    "Pinned:",
    {name: importlib.metadata.version(name) for name in PINNED_TRANS},
)
print("Core runtime ready / بيئة Core جاهزة")


def softmax(x: np.ndarray, axis: int = -1) -> np.ndarray:
    shifted = x - np.max(x, axis=axis, keepdims=True)
    exp_x = np.exp(shifted)
    return exp_x / exp_x.sum(axis=axis, keepdims=True)


def scaled_dot_product_attention(
    q: np.ndarray,
    k: np.ndarray,
    v: np.ndarray,
    keep_mask: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if q.shape[-1] != k.shape[-1]:
        raise ValueError("Q and K must share d_k")

    if k.shape[-2] != v.shape[-2]:
        raise ValueError("K and V must share sequence length")

    scores = q @ np.swapaxes(k, -1, -2) / math.sqrt(q.shape[-1])

    if keep_mask is not None:
        mask = np.asarray(keep_mask, dtype=bool)

        try:
            mask = np.broadcast_to(mask, scores.shape)
        except ValueError as exc:
            raise ValueError(
                "keep_mask is not broadcastable to scores"
            ) from exc

        if np.any(mask.sum(axis=-1) == 0):
            raise ValueError("Every query row must keep at least one key")

        scores = np.where(mask, scores, -np.inf)

    weights = softmax(scores, axis=-1)
    output = weights @ v

    return output, weights, scores


q = np.array([
    [1.0, 0.0],
    [0.0, 1.0],
])

k = np.array([
    [1.0, 0.0],
    [0.0, 1.0],
    [1.0, 1.0],
])

v = np.array([
    [10.0, 0.0],
    [0.0, 10.0],
    [5.0, 5.0],
])

output, weights, scores = scaled_dot_product_attention(q, k, v)

print("scores shape:", scores.shape)
print("weights:\n", np.round(weights, 3))
print("row sums:", weights.sum(axis=-1))
print("output:\n", np.round(output, 3))

assert output.shape == (2, 2)
assert np.allclose(weights.sum(axis=-1), 1.0)

print("Scaled attention=PASS")


def entropy(probabilities: np.ndarray) -> float:
    p = np.clip(probabilities, 1e-12, 1.0)
    return float(-np.sum(p * np.log(p), axis=-1).mean())


q_big = rng.normal(size=(6, 64))
k_big = rng.normal(size=(6, 64))

raw_scores = q_big @ k_big.T
unscaled_weights = softmax(raw_scores)
scaled_weights = softmax(raw_scores / math.sqrt(q_big.shape[-1]))

print(
    "mean entropy without scaling:",
    round(entropy(unscaled_weights), 3),
)

print(
    "mean entropy with scaling:",
    round(entropy(scaled_weights), 3),
)

print("Scaling comparison complete")


causal_keep_mask = np.tril(np.ones((2, 3), dtype=bool))

masked_output, masked_weights, _ = scaled_dot_product_attention(
    q,
    k,
    v,
    keep_mask=causal_keep_mask,
)

print("keep mask:\n", causal_keep_mask.astype(int))
print("masked weights:\n", np.round(masked_weights, 3))

assert masked_weights[0, 1] == 0.0
assert masked_weights[0, 2] == 0.0

print("Mask semantics=PASS")


def split_heads(x: np.ndarray, num_heads: int) -> np.ndarray:
    batch, seq_len, d_model = x.shape
    if d_model % num_heads != 0:
        raise ValueError("d_model must be divisible by num_heads")
    d_head = d_model // num_heads
    return x.reshape(batch, seq_len, num_heads, d_head).transpose(0, 2, 1, 3)


def combine_heads(x: np.ndarray) -> np.ndarray:
    batch, num_heads, seq_len, d_head = x.shape
    return x.transpose(0, 2, 1, 3).reshape(batch, seq_len, num_heads * d_head)


x = rng.normal(size=(2, 5, 12))

heads = split_heads(x, num_heads=3)
combined = combine_heads(heads)

print("input:", x.shape)
print("split:", heads.shape, "= (batch, heads, tokens, d_head)")
print("combined:", combined.shape)

assert heads.shape == (2, 3, 5, 4)
assert np.allclose(combined, x)

print("Multi-head shape journey=PASS")


try:
    import torch

    torch.manual_seed(SEED)

    layer = torch.nn.TransformerEncoderLayer(
        d_model=12,
        nhead=3,
        dim_feedforward=24,
        dropout=0.0,
        batch_first=True,
        norm_first=False,
    )
    layer.eval()

    torch_x = torch.tensor(x, dtype=torch.float32)

    with torch.no_grad():
        encoder_output = layer(torch_x)

    print("PyTorch encoder output:", tuple(encoder_output.shape))
    assert tuple(encoder_output.shape) == (2, 5, 12)
    print("Optional encoder layer=PASS")

except ModuleNotFoundError:
    print("PyTorch is optional here; NumPy Core remains complete.")


try:
    import torch
    import torch.nn.functional as F

    tq = torch.tensor(q, dtype=torch.float64)[None, None, :, :]
    tk = torch.tensor(k, dtype=torch.float64)[None, None, :, :]
    tv = torch.tensor(v, dtype=torch.float64)[None, None, :, :]

    torch_result = F.scaled_dot_product_attention(
        tq, tk, tv, dropout_p=0.0
    )

    np_result = output[None, None, :, :]
    max_difference = float(
        np.max(np.abs(torch_result.numpy() - np_result))
    )

    print("max NumPy/PyTorch difference:", f"{max_difference:.3e}")
    assert max_difference < 1e-9
    print("NumPy/PyTorch parity=PASS")

except ModuleNotFoundError:
    print("PyTorch unavailable; parity check skipped without affecting Core.")


from transformers import AutoConfig

AUDIT_CHECKPOINTS = [
    "google-bert/bert-base-multilingual-cased",
    "CAMeL-Lab/bert-base-arabic-camelbert-da",
]

EXPECTED_TOTALS = {
    "google-bert/bert-base-multilingual-cased": 177_853_440,
    "CAMeL-Lab/bert-base-arabic-camelbert-da": 109_081_344,
}


def bert_parameter_audit(model_id: str) -> dict:
    config = AutoConfig.from_pretrained(model_id)
    assert config.model_type == "bert"

    hidden = config.hidden_size
    intermediate = config.intermediate_size

    embeddings = (
        config.vocab_size * hidden
        + config.max_position_embeddings * hidden
        + config.type_vocab_size * hidden
        + 2 * hidden
    )

    per_layer = (
        3 * (hidden * hidden + hidden)
        + (hidden * hidden + hidden)
        + 2 * hidden
        + (hidden * intermediate + intermediate)
        + (intermediate * hidden + hidden)
        + 2 * hidden
    )

    pooler = hidden * hidden + hidden
    total = embeddings + config.num_hidden_layers * per_layer + pooler

    return {
        "model_id": model_id,
        "vocab_size": config.vocab_size,
        "total_parameters": total,
        "embedding_share": embeddings / total,
    }


parameter_audits = [
    bert_parameter_audit(model_id) for model_id in AUDIT_CHECKPOINTS
]

for item in parameter_audits:
    print(
        f'{item["model_id"]} | '
        f'vocab={item["vocab_size"]:,} | '
        f'total={item["total_parameters"]:,} | '
        f'embeddings={item["embedding_share"]:.1%}'
    )

assert all(
    item["total_parameters"] == EXPECTED_TOTALS[item["model_id"]]
    for item in parameter_audits
)

print("TWO_CHECKPOINT_PARAMETER_AUDIT=PASS")


import matplotlib.pyplot as plt
from transformers import AutoModel, AutoTokenizer
from transformers.utils import logging as hf_logging

hf_logging.set_verbosity_error()

ACTUAL_MODEL_ID = "distilbert/distilbert-base-multilingual-cased"

actual_tokenizer = AutoTokenizer.from_pretrained(
    ACTUAL_MODEL_ID,
    use_fast=True,
)

actual_model = AutoModel.from_pretrained(
    ACTUAL_MODEL_ID,
    attn_implementation="eager",
)
actual_model.eval()

sentences = [
    "الخدمة لم تتأخر.",
    "The service was not delayed.",
]

encoded = actual_tokenizer(
    sentences,
    padding=True,
    truncation=True,
    max_length=32,
    return_tensors="pt",
)

with torch.no_grad():
    forward = actual_model(
        **encoded,
        output_attentions=True,
    )

parameter_count = sum(parameter.numel() for parameter in actual_model.parameters())
attention_shape = tuple(forward.attentions[0].shape)
hidden_shape = tuple(forward.last_hidden_state.shape)
arabic_tokens = actual_tokenizer.convert_ids_to_tokens(encoded["input_ids"][0])
valid_length = int(encoded["attention_mask"][0].sum())

head_weights = (
    forward.attentions[0][0, 0, :valid_length, :valid_length].cpu().numpy()
)

print(f"Model: {ACTUAL_MODEL_ID}")
print(f"Parameters: {parameter_count:,}")
print("Hidden-state shape:", hidden_shape)
print("Attention tensor [batch, heads, query, key]:", attention_shape)
print("Arabic tokens:", arabic_tokens[:valid_length])
print(
    "Row-sum range:",
    float(head_weights.sum(-1).min()),
    float(head_weights.sum(-1).max()),
)

figure, axis = plt.subplots(figsize=(8, 6))

image = axis.imshow(
    head_weights,
    cmap="Blues",
    vmin=0.0,
)

axis.set_xticks(
    range(valid_length),
    arabic_tokens[:valid_length],
    rotation=60,
    ha="right",
)

axis.set_yticks(
    range(valid_length),
    arabic_tokens[:valid_length],
)

axis.set_xlabel("Key token")
axis.set_ylabel("Query token")
axis.set_title("Layer 1 · Head 1 · descriptive attention weights")

figure.colorbar(image, ax=axis, fraction=0.046)
figure.tight_layout()
plt.show()

assert parameter_count > 100_000_000
assert hidden_shape[:2] == tuple(encoded["input_ids"].shape)
assert attention_shape[0] == 2
assert attention_shape[2] == attention_shape[3]
assert np.allclose(head_weights.sum(-1), 1.0, atol=1e-5)

print("ACTUAL_TRANSFORMER_FORWARD=PASS")


core_checks_final = {
    "weights_sum_to_one": np.allclose(weights.sum(axis=-1), 1.0),
    "two_checkpoint_parameter_audit": (
        len(parameter_audits) == 2
        and all(
            item["total_parameters"] == EXPECTED_TOTALS[item["model_id"]]
            for item in parameter_audits
        )
    ),
    "actual_forward": (
        parameter_count > 100_000_000 and len(forward.attentions) > 0
    ),
    "output_shape": output.shape == (2, 2),
    "masked_positions_zero": (
        masked_weights[0, 1] == 0 and masked_weights[0, 2] == 0
    ),
    "heads_round_trip": np.allclose(combined, x),
}

for name, passed in core_checks_final.items():
    print(f"{name}: {'PASS' if passed else 'FAIL'}")

assert all(core_checks_final.values())